---
title: "The Whole Truth"
subtitle: "A PhD in Industry"
author: "Dr. Michael Mullarkey"
format:
  revealjs:
    incremental: true
    theme: blood
    transition: fade
    background-transition: fade
    transition-speed: slow
    chalkboard:
      chalk-effect: 0.25
      boardmarker-width: 5
---

# Need to Say

# {background-image="images/phd_unemployment.png" background-size="contain" background-repeat="no-repeat"}

# Feels Like We're All Screwed {background-image="images/phd_unemployment.png" background-size="contain" background-repeat="no-repeat" background-opacity="0.7"}

# A map just in case

# {background-image="images/blurred_linkedin.jpg" background-size="contain" background-repeat="no-repeat"}

# Oh No {background-image="images/blurred_linkedin.jpg" background-size="contain" background-repeat="no-repeat" background-opacity="0.7"}

```{css}
.center h1 {
  text-align: center;
}
```

# I Had a Hard Time

# I Had Serious Advantages

# I Don't Have a Time Machine

# My Path Isn't Replicable

# And Still

# Better Work-Life Balance

# Location Flexibility

# $$$

# {background-image="images/blurred_linkedin.jpg" background-size="contain" background-repeat="no-repeat"}

# What's a Non-BS Version of This Post? {background-image="images/blurred_linkedin.jpg" background-size="contain" background-repeat="no-repeat" background-opacity="0.7"}

# This Talk (Hopefully!)

# Agenda

- Identifying roles
- Converting CV to resume
- Networking
- Enhancing + acquiring skills
- Portfolio work
- Applying
- Interviewing
- Negotiating
- Q&A

# End to End vs. Deep-Dive

# End to End

## More in-depth resources at end of each section {.center}

```{css}
.center h2 {
  text-align: center;
}
```

# Identifying Roles

# Favorite Part?

# Favorite Overlap?

# Probably a Role

# Search LinkedIn

# Most People "Leave"

# Where Did They End Up?

# Go Outside Common Titles

# Resources

- [Job titles for social scientists ](https://hkotek.com/blog/altac-jobs-for-social-scientists/){preview-link="true" style="text-align: center"}
- [Jobs to search for](https://www.linkedin.com/pulse/what-jobs-do-i-search-social-science-degree-anna-hartley/){preview-link="true" style="text-align: center"}
- [levels.fyi job board](https://www.levels.fyi/jobs?from=subnav){preview-link="true" style="text-align: center"}
- [flexjobs job board](https://www.flexjobs.com/){preview-link="true" style="text-align: center"}

# Converting CV to Resume

# One Page

# Use a Free Template

# Make in Easy to Tailor Format

# Compare to Job Description

# Can Inform Skills Phase

## Talk business value first, then how you achieved it {.center}

```{css}
.center h2 {
  text-align: center;
}
```

## Built a custom LLM to extract clinical insights {.center}

```{css}
.center h2 {
  text-align: center;
}
```

## Unlocked ~30% more top-of-funnel ARR by building a custom LLM for extracting clinical insights {.center}

```{css}
.center h2 {
  text-align: center;
}
```

# Here's Mine

::: {style="text-align: center; margin-top: 1em"}
[MY RESUME](https://mcmullarkey.github.io/assets/mcmullarkey_resume_website.pdf){preview-link="true" style="text-align: center"}
:::

# Resources

- [Template I used](https://blog.pragmaticengineer.com/the-pragmatic-engineers-resume-template/){preview-link="true" style="text-align: center"}
- [UC Davis CV to resume workshop](https://icc.ucdavis.edu/materials/resume/cv/convertingcv){preview-link="true" style="text-align: center"}
- [Indeed CV to resume tutorial](https://www.indeed.com/career-advice/resumes-cover-letters/how-to-convert-academic-cv-for-industry-positions){preview-link="true" style="text-align: center"}

# Networking

# Everyone's Favorite

# Common Interests

# Slacks

# Discord Servers?

# Twitch Channels??

# Meetups

# I Regret to Inform You

# LinkedIn

# Start Small

# Remember common interests

# Resources

- [Data Science Learning Community](https://dslc.io/){preview-link="true" style="text-align: center"}
- [Approaching Significance Discord](https://discord.gg/9xkE2tnhnH){preview-link="true" style="text-align: center"}
- [Nick Wan Twitch](https://www.twitch.tv/nickwan_datasci){preview-link="true" style="text-align: center"}

# Skills

# You Have A Lot

# Need to Translate

# Need More

# Coding Especially

# Data Science Specific

# SQL

# Python

# Version Control

# And Honestly

# Software Engineering

# How?

# Deprioritize

# Try Free First

# Sample Resources

# Get a Feel

# Resources

- [SQL Lemur 30 Day](https://datalemur.com/blog/learn-sql-in-30-days-roadmap){preview-link="true" style="text-align: center"}
- [Data Science at the Command Line](https://jeroenjanssens.com/dsatcl/){preview-link="true" style="text-align: center"}
- [Docker crash course](https://www.youtube.com/watch?v=pg19Z8LL06w){preview-link="true" style="text-align: center"}
- [CS50x lectures](https://www.youtube.com/playlist?list=PLhQjrBD2T380F_inVRXMIHCqLaNUd7bN4){preview-link="true" style="text-align: center"}
- [Pracical deep learning for coders](https://course.fast.ai/){preview-link="true" style="text-align: center"}

# Portfolio

# Show You Can Deliver

# Needs to Be Fun

# Can Fill In

# Here's Mine

::: {style="text-align: center; margin-top: 1em"}
[MY PORTFOLIO](https://mcmullarkey.github.io/){preview-link="true" style="text-align: center"}
:::

# Maybe Not Necessary

# Even More Grifts Here

# Resources

- [Build a Career in Data Science podcast](https://podcast.bestbook.cool/){preview-link="true" style="text-align: center"}
- [User Experience Research portfolio tutorial](https://www.userinterviews.com/blog/ux-research-portfolio-examples-templates){preview-link="true" style="text-align: center"}

# Applying

# Referrals

# Networking Can Pay Off

# Ideally before you need a job

# They likely get $$$

# Don't Go Too Hard

# Cold Apps

# Tailor Resume

# I Know

# It's Worth It

# Create Tailor-able Cover Letter

# Target a Variety of Job Boards

# Pacing

# Interviews

# Often Many

# Varies Widely

# Two Types

# Behavioral

# Technical

# For Behavioral

# STAR Framework

# Situation

# Task

# Action

# Resolution

# For Technical

# Practice

# Can Ask Internal Recruiter

# Show Thought Process

# Don't Have to Ace

# Have gotten harder

# Resources

- [MIT STAR tutorial](https://capd.mit.edu/resources/the-star-method-for-behavioral-interviews/){preview-link="true" style="text-align: center"}
- [Penn technical interview tutorial](https://careerdevelopment.princeton.edu/guides/interviews/technical-interview-preparation){preview-link="true" style="text-align: center"}
- [Realistic Recruiter TikTok](https://www.tiktok.com/@realisticrecruiting?lang=en){preview-link="true" style="text-align: center"}

# Negotiating

# Starts Early

# Seek Out Info

# Recruiter Call

# Looking for a Good Fit

# Even a Range Would Help

# Verbal Offer

# They Expect It

# No?

# Red Flag

# Not Limited to Base Salary

# Equity

# Work from Home

# Etc.

# Resources

- [levels.fyi salary transparency](https://www.levels.fyi/t){preview-link="true" style="text-align: center"}
- [Indeed negotiation tutorial](https://www.indeed.com/career-advice/pay-salary/how-to-negotiate-salary){preview-link="true" style="text-align: center"}

# Summary

## We all work for companies {.center}

```{css}
.center h2 {
  text-align: center;
}
```

## A dream job is still a job {.center}

```{css}
.center h2 {
  text-align: center;
}
```

## Hard for academic positions to compete solely as jobs {.center}

```{css}
.center h2 {
  text-align: center;
}
```

## As difficult as this process is, can happen anytime {.center}

```{css}
.center h2 {
  text-align: center;
}
```

# Thanks!

# Q&A


```{r}
#| echo: false
#| eval: false

1+1

```
